using System.Collections.Generic;
using System.Linq;
using System.Text;
using MegatonHammer.Editor;

namespace MegatonHammer.Export;

/// <summary>
/// Generates <c>mh_dialogue_data.c</c> — the <c>gMhDialogueTable[]</c> the portable <c>ovl_En_MhTalk</c>
/// actor reads (matches <c>portable/ovl_En_MhTalk/mh_dialogue.h</c>). This carries only BEHAVIOUR
/// (branch / give item / charge rupees / set flag / fulfilled fallback / sfx / gesture); presentation is in
/// the normal message bytes. A message gets a row only if it actually has behaviour.
/// </summary>
public static class MhDialogueDataWriter
{
    public static string Write(IEnumerable<MhMessage> messages)
    {
        var rows = messages.Where(m => m.IsOverride && NeedsEntry(m)).OrderBy(m => m.Id).ToList();
        var sb = new StringBuilder();
        sb.AppendLine("/* Generated by Megaton Hammer - do not edit by hand.");
        sb.AppendLine(" * Behaviour table for the portable ovl_En_MhTalk actor (see portable/README.md). */");
        sb.AppendLine("#include \"mh_dialogue.h\"");
        sb.AppendLine();
        sb.AppendLine("const MhDialogueEntry gMhDialogueTable[] = {");
        foreach (var m in rows) sb.AppendLine("    " + Row(m));
        sb.AppendLine("};");
        sb.AppendLine($"const s32 gMhDialogueCount = {rows.Count};");
        return sb.ToString();
    }

    /// <summary>A message needs a data row only if it has behaviour beyond plain presentation.</summary>
    public static bool NeedsEntry(MhMessage m) =>
        m.Kind == MhMsgKind.Prompt || !m.Outcome1.IsEmpty || !m.Outcome2.IsEmpty ||
        m.Sfx >= 0 || m.Gesture >= 0 || m.DoneFlag >= 0;

    private static string Row(MhMessage m)
    {
        int sfx = m.Sfx < 0 ? 0 : m.Sfx;
        int kind = m.Kind == MhMsgKind.Prompt ? 1 : 0;
        return $"{{ 0x{m.Id:X4}, 0x{sfx:X4}, {m.Gesture}, {kind}, " +
               $"{{ {Out(m.Outcome1)}, {Out(m.Outcome2)} }}, {m.DoneFlag}, {m.AfterMsgId} }},";
    }

    private static string Out(MhOutcome o)
    {
        int rupees = o.ChargeRupees ? o.RupeeCost : 0;
        return $"{{ {o.NextMsgId}, {o.FireFlag}, {o.GiveItem}, {rupees} }}";
    }
}
